SELECT TABLE_NAME, CONSTRAINT_NAME  
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS  
WHERE CONSTRAINT_TYPE = 'PRIMARY KEY';

ALTER TABLE Dim_DailySales
DROP CONSTRAINT PK__Dim_Dail__5877C2FEDD9E3BA7;

ALTER TABLE Dim_BikeBrands
DROP CONSTRAINT PK_BikeBrands;

ALTER TABLE Dim_StoreSales
DROP CONSTRAINT PK__Dim_Stor__ADC1E1AD0F4A2C6F;

ALTER TABLE Dim_StaffSales
DROP CONSTRAINT PK__Dim_Staf__37D30BF49526B68F;

ALTER TABLE Dim_BikeBrands
ALTER COLUMN brand_id INT NOT NULL;

ALTER TABLE Dim_BikeBrands
ALTER COLUMN TimeOfYear VARCHAR(50) NOT NULL;


ALTER TABLE Dim_BikeBrands
ADD CONSTRAINT PK_BikeBrands PRIMARY KEY (brand_id, TimeOfYear);

ALTER TABLE Dim_DailySales ADD TimeKey INT IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE Dim_BikeBrands ADD BrandKey decimal(1)IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE Dim_StoreSales ADD StoreKey INT IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE Dim_StaffSales ADD StaffKey INT IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Dim_DailySales
DROP CONSTRAINT PK_Dim_DailySales;

Drop table Fact_Sales;

ALTER TABLE Dim_BikeBrands
ADD BrandKey DECIMAL(20,0) IDENTITY(1,1) NOT NULL;


ALTER TABLE Dim_DailySales
ADD TimeKey DECIMAL(20,0) IDENTITY(1,1) NOT NULL;

ALTER TABLE Dim_StaffSales
ADD StaffKey DECIMAL(20,0) IDENTITY(1,1) NOT NULL;

ALTER TABLE Dim_StoreSales
ADD StoreKey DECIMAL(20,0) IDENTITY(1,1) NOT NULL;


-- Add primary key to Dim_Date
ALTER TABLE Dim_DailySales
ADD CONSTRAINT PK_Dim_DailySales PRIMARY KEY (TimeKey);

-- Add primary key to Dim_Store
ALTER TABLE Dim_StoreSales
ADD CONSTRAINT PK_Dim_StoreSales PRIMARY KEY (StoreKey);

-- Add primary key to Dim_Staff
ALTER TABLE Dim_StaffSales
ADD CONSTRAINT PK_Dim_StaffSales PRIMARY KEY (StaffKey);

-- Add primary key to Dim_Brand
ALTER TABLE Dim_BikeBrands
ADD CONSTRAINT PK_Dim_BikeBrands PRIMARY KEY (BrandKey);
